### ISSUE TITLE
OpenCV person recognition

### ISSUE THREAD

**Issue by GitRaka** [cu-ecen-5013/final-project-IMNG7#2]
Creation and development of python based scripts and application for person recognition.
DoD: People successfully counted.
Blockers: None

**Comment by IMNG7** [comment]
People counter completed with output in the git directory.

**Comment by IMNG7** [comment]
Github Link:https://github.com/cu-ecen-5013/final-project-IMNG7/commit/862281682d2b28baca4d9a10001c27a566cf2079
