### ISSUE TITLE
Buildroot Build for BeagleBone Black

### ISSUE THREAD

**Issue by IMNG7** [cu-ecen-5013/final-project-IMNG7#8]
This issue resolving, involves the configuration of the BeagleBone Black for Buildroot image setup. The basic linux image without any add-ons would be loaded on the BeagleBone board and the custom image booted up on it successfully to have a ready system.

**Comment by GitRaka** [comment]
Successfully launched the custom buildroot image into the BBB. Issues related to rufus was faced and resolved with Win32image writer.
